# Site settings
title: Devon Burriss' Blog
header-img: "img/backgrounds/explore-bg.jpg"
copyright_name: "Devon Burriss"
description: "Mostly explorations in code"
author: "Devon Burriss"

baseurl: "/"
url: "https://devonburriss.me/"
is_production: true

twitter_username: DevonBurriss
github_username: dburriss
disqus_username: devonburriss

# Google Analytics
google_tracking_id: UA-45750611-2

# Related posts configuration (used by F# SiteRenderer)
similar_posts:
    filter_threshold: 0.3
    related_count: 3
    weight:
        categories: 0.1
        tags: 0.3
        title: 0.2
        text: 1